version: 1.0.9.{build}
build:
  verbosity: minimal
after_build:
- ps: 7z a SMEncounterRNGTool.zip .\SMEncounterRNGTool\bin\Debug\SMEncounterRNGTool.exe
artifacts:
- path: SMEncounterRNGTool.zip
  name: SMEncounterRNGTool